### PR TITLE
feat: add cli args for better output dir/filename handling

### PR DESCRIPTION
**Pull request by jjo**
* Add several CLI args, to let the user customize output tree:
```
   --outdir value        output dir (default: "generated")
   --template_sel value  pre-set template to use (default: "tpl_flat")
   --tpl_flat outdir     tpl_flat gotemplate (.X.Outdir is set to outdir
flag) (default:
"{{.X.Outdir}}/{{.Metadata.Name}}-{{.X.ShortKind}}.yaml")
   --tpl_ns value        tpl_ns gotemplate (.X.NS equals
.Metadata.Namespace or '_no_ns_' if unset) (default:
"{{.X.Outdir}}/{{.X.NS}}/{{.Metadata.Name}}.{{.Kind}}.yaml")
   --name_re value       Kubernetes API metadata.name to match (default:
"^[^./]+$")
   --namespace_re value  Kubernetes API metadata.namespace to match
(default: "^(|[a-z0-9]([-a-z0-9]*[a-z0-9])?)$")
   --kind_re value       Kubernetes API kind to match (default:
"^[0-9a-zA-Z]+$")
   --file_re value       final output file regex to match (default:
".+")
```
* See `Readme.md` for some example usage(s).
* Update and commit `vendor/` (to improve builds reproduce-ability)

### CODE REVIEW

**Comment by jjo** [comment]
Fixes #4

**Comment by mogensen** [comment]
Hi @jjo 

Thanks for the contribution. I will try to look through it in the coming week.

This project used the new go modules for dependency management, and i would therefore prefer to not have a `vendor` folder. Could you send a an update to the PR without this?

Thanks again! :smile:

**Comment by jjo** [comment]
> This project used the new go modules for dependency management, and i would therefore prefer to not have a `vendor` folder. Could you send a an update to the PR without this?

Sure, done.

> 
> Thanks again! smile

Thank you in the 1st place for the tool !

**Comment by jjo** [comment]
Thanks @mogensen for the merge, appreciate if you can cut a new release, time permits.
Cheers --jjo

**Pull request merged**
